/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.retrorobots.playerGUI;

import com.retrorobots.ServerConnectorFactory;
import org.json.JSONArray;
import org.json.JSONObject;

/**
 *
 * @author KeeganRiley
 */
public class AnswerPanel extends javax.swing.JPanel {

    private PlayerWindow pw;

    /**
     * Creates new form AnswerPanel
     */
    public AnswerPanel() {
        initComponents();
        this.pw = null;
    }

    public AnswerPanel(PlayerWindow pw) {
        this();
        this.pw = pw;
        this.submitAnswerButton.setEnabled(false);
    }

    public void enableAnswer() {
        this.submitAnswerButton.setEnabled(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jTextField1 = new javax.swing.JTextField();
        submitAnswerButton = new javax.swing.JButton();

        setLayout(new java.awt.GridBagLayout());

        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setText("Enter Answer:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.3;
        gridBagConstraints.insets = new java.awt.Insets(15, 15, 15, 15);
        add(jTextField1, gridBagConstraints);

        submitAnswerButton.setText("Submit");
        submitAnswerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitAnswerButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(15, 15, 15, 15);
        add(submitAnswerButton, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void submitAnswerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitAnswerButtonActionPerformed

        String data = this.jTextField1.getText();
        String returnData = ServerConnectorFactory.queryServer(ServerConnectorFactory.VERIFY_ANSWER_PATH+"?ans="+data);
        JSONObject anRes = new JSONObject(returnData);
        boolean correct = anRes.getBoolean("result");

        JSONObject game = anRes.getJSONObject("game");
        JSONArray players = game.getJSONArray("playerList");

        int spinsLeft = game.getInt("spinCount");
        int quesLeft = game.getInt("quesCount");

        if (spinsLeft <= 0 || quesLeft <= 0) {
            String end = ServerConnectorFactory.queryServer("/checkRound");
            if (end.equalsIgnoreCase("end of Game")) {
                this.pw.endGame(game);
                this.submitAnswerButton.setEnabled((false));
                return;
            }
            this.pw.endRound();
            this.submitAnswerButton.setEnabled(false);
            return;
        }

        if (correct) {
            this.pw.spinAgain();
        } else {
            this.submitAnswerButton.setEnabled(false);
            JSONObject currP = game.getJSONObject("currPlayer");
            this.pw.switchPlayers(currP.getString("name"));
        }
        this.pw.updatePlayers(players);
        this.pw.updateGame(game);

    }//GEN-LAST:event_submitAnswerButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton submitAnswerButton;
    // End of variables declaration//GEN-END:variables
}
