/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.retrorobots.playerGUI;

import com.retrorobots.ServerConnectorFactory;

/**
 *
 * @author KeeganRiley
 */
public class QuestionPanel extends javax.swing.JPanel {

    private PlayerWindow pw;

    /**
     * Creates new form QuestionPanel
     */
    public QuestionPanel() {
        initComponents();
        getNewQuestionButton.setVisible(false);
        this.pw = null;
    }

    public QuestionPanel(PlayerWindow pw) {
        this();
        this.pw = pw;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        questionLabel = new javax.swing.JLabel();
        getNewQuestionButton = new javax.swing.JButton();

        setLayout(new java.awt.GridBagLayout());

        questionLabel.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        questionLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        questionLabel.setText("question");
        questionLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.4;
        gridBagConstraints.insets = new java.awt.Insets(15, 15, 15, 15);
        add(questionLabel, gridBagConstraints);

        getNewQuestionButton.setText("Get New Question");
        getNewQuestionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getNewQuestionButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(getNewQuestionButton, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void getNewQuestionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getNewQuestionButtonActionPerformed

        String content = ServerConnectorFactory.queryServer(ServerConnectorFactory.QUESTION_PATH);
        String labelFormat = "<html><body style='text-align: center; width: %1spx'>%1s";
        this.questionLabel.setText(String.format(labelFormat, 300, content.toString()));
        
    }//GEN-LAST:event_getNewQuestionButtonActionPerformed

    public void updateQuestion(String data) {
        String labelFormat = "<html><body style='text-align: center; width: %1spx'>%1s";
        this.questionLabel.setText(String.format(labelFormat, 300, data.toString()));
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton getNewQuestionButton;
    private javax.swing.JLabel questionLabel;
    // End of variables declaration//GEN-END:variables
}
