/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.retrorobots.playerGUI.gameBoard;

import org.json.JSONArray;
import org.json.JSONObject;

import javax.swing.*;
import javax.swing.border.Border;
import java.awt.*;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 *
 * @author KeeganRiley
 */
public class MainGameBoard extends javax.swing.JPanel {

    private List<JLabel> catNames = new ArrayList<>();
    private JPanel[][] cardPanels = new JPanel[5][5];
    private List<JSONObject> categoryList;
    private Map<String, Integer> columns = new HashMap<>();
    private Map<JPanel, ValueCard> cells = new HashMap<>();

    /**
     * Creates new form MainPanel
     */
    public MainGameBoard(List<JSONObject> list) {
        this.categoryList = list;
        initComponents();
        init();
    }

    private void init() {
        catNames.add(category1Label);
        catNames.add(category2Label);
        catNames.add(category3Label);
        catNames.add(category4Label);
        catNames.add(category5Label);

        cardPanels[0][0] = c1OnePanel;
        cardPanels[0][1] = c1TwoPanel;
        cardPanels[0][2] = c1ThreePanel;
        cardPanels[0][3] = c1FourPanel;
        cardPanels[0][4] = c1FivePanel;
        cardPanels[1][0] = c2OnePanel;
        cardPanels[1][1] = c2TwoPanel;
        cardPanels[1][2] = c2ThreePanel;
        cardPanels[1][3] = c2FourPanel;
        cardPanels[1][4] = c2FivePanel;
        cardPanels[2][0] = c3OnePanel;
        cardPanels[2][1] = c3TwoPanel;
        cardPanels[2][2] = c3ThreePanel;
        cardPanels[2][3] = c3FourPanel;
        cardPanels[2][4] = c3FivePanel;
        cardPanels[3][0] = c4OnePanel;
        cardPanels[3][1] = c4TwoPanel;
        cardPanels[3][2] = c4ThreePanel;
        cardPanels[3][3] = c4FourPanel;
        cardPanels[3][4] = c4FivePanel;
        cardPanels[4][0] = c5OnePanel;
        cardPanels[4][1] = c5TwoPanel;
        cardPanels[4][2] = c5ThreePanel;
        cardPanels[4][3] = c5FourPanel;
        cardPanels[4][4] = c5FivePanel;


        makeBoard();
    }

    public void makeBoard() {
        for(int i = 0; i < 5; i++) {
            JSONObject category = this.categoryList.get(i);
            String name = category.getString("categoryName");
            catNames.get(i).setText(name);
            columns.put(name, i);
            JSONArray questionList = category.getJSONArray("questions");
            for (int j = 0; j < 5; j++) {
                JSONObject question = questionList.getJSONObject(j);
                ValueCard vc = new ValueCard(question);
                JPanel card = cardPanels[i][j];
                card.setLayout(new BorderLayout());
                card.add(vc, BorderLayout.CENTER);
                cells.put(card, vc);
            }
        }
        this.revalidate();
    }

    public void updateBoard(JSONObject question) {
        String cat = question.getString("category");
        int qNum = question.getInt("questionNumber");
        int colNum = columns.get(cat);
        cells.get(cardPanels[colNum][qNum]).setAnswered(true);
    }

    public void setCategoryList(List<JSONObject> list) {
        this.categoryList = list;
    }

    public void newRound() {
        makeBoard();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        category1Label = new javax.swing.JLabel();
        category2Label = new javax.swing.JLabel();
        category3Label = new javax.swing.JLabel();
        category4Label = new javax.swing.JLabel();
        category5Label = new javax.swing.JLabel();
        c1OnePanel = new javax.swing.JPanel();
        c1TwoPanel = new javax.swing.JPanel();
        c1ThreePanel = new javax.swing.JPanel();
        c1FourPanel = new javax.swing.JPanel();
        c1FivePanel = new javax.swing.JPanel();
        c2OnePanel = new javax.swing.JPanel();
        c2TwoPanel = new javax.swing.JPanel();
        c2ThreePanel = new javax.swing.JPanel();
        c2FourPanel = new javax.swing.JPanel();
        c2FivePanel = new javax.swing.JPanel();
        c3OnePanel = new javax.swing.JPanel();
        c3TwoPanel = new javax.swing.JPanel();
        c3ThreePanel = new javax.swing.JPanel();
        c3FourPanel = new javax.swing.JPanel();
        c3FivePanel = new javax.swing.JPanel();
        c4OnePanel = new javax.swing.JPanel();
        c4TwoPanel = new javax.swing.JPanel();
        c4ThreePanel = new javax.swing.JPanel();
        c4FourPanel = new javax.swing.JPanel();
        c4FivePanel = new javax.swing.JPanel();
        c5OnePanel = new javax.swing.JPanel();
        c5TwoPanel = new javax.swing.JPanel();
        c5ThreePanel = new javax.swing.JPanel();
        c5FourPanel = new javax.swing.JPanel();
        c5FivePanel = new javax.swing.JPanel();

        setLayout(new java.awt.GridBagLayout());

        category1Label.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        category1Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        category1Label.setText("cat 1");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(category1Label, gridBagConstraints);

        category2Label.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        category2Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        category2Label.setText("cat 2");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(category2Label, gridBagConstraints);

        category3Label.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        category3Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        category3Label.setText("cat 3");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(category3Label, gridBagConstraints);

        category4Label.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        category4Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        category4Label.setText("cat 4");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(category4Label, gridBagConstraints);

        category5Label.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        category5Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        category5Label.setText("cat 5");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(category5Label, gridBagConstraints);

        javax.swing.GroupLayout c1OnePanelLayout = new javax.swing.GroupLayout(c1OnePanel);
        c1OnePanel.setLayout(c1OnePanelLayout);
        c1OnePanelLayout.setHorizontalGroup(
            c1OnePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 157, Short.MAX_VALUE)
        );
        c1OnePanelLayout.setVerticalGroup(
            c1OnePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 64, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.2;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(c1OnePanel, gridBagConstraints);

        javax.swing.GroupLayout c1TwoPanelLayout = new javax.swing.GroupLayout(c1TwoPanel);
        c1TwoPanel.setLayout(c1TwoPanelLayout);
        c1TwoPanelLayout.setHorizontalGroup(
            c1TwoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 157, Short.MAX_VALUE)
        );
        c1TwoPanelLayout.setVerticalGroup(
            c1TwoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 160, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.2;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(c1TwoPanel, gridBagConstraints);

        javax.swing.GroupLayout c1ThreePanelLayout = new javax.swing.GroupLayout(c1ThreePanel);
        c1ThreePanel.setLayout(c1ThreePanelLayout);
        c1ThreePanelLayout.setHorizontalGroup(
            c1ThreePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 157, Short.MAX_VALUE)
        );
        c1ThreePanelLayout.setVerticalGroup(
            c1ThreePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 64, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.2;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(c1ThreePanel, gridBagConstraints);

        javax.swing.GroupLayout c1FourPanelLayout = new javax.swing.GroupLayout(c1FourPanel);
        c1FourPanel.setLayout(c1FourPanelLayout);
        c1FourPanelLayout.setHorizontalGroup(
            c1FourPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 157, Short.MAX_VALUE)
        );
        c1FourPanelLayout.setVerticalGroup(
            c1FourPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 64, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.2;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(c1FourPanel, gridBagConstraints);

        javax.swing.GroupLayout c1FivePanelLayout = new javax.swing.GroupLayout(c1FivePanel);
        c1FivePanel.setLayout(c1FivePanelLayout);
        c1FivePanelLayout.setHorizontalGroup(
            c1FivePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 157, Short.MAX_VALUE)
        );
        c1FivePanelLayout.setVerticalGroup(
            c1FivePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 64, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.2;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(c1FivePanel, gridBagConstraints);

        javax.swing.GroupLayout c2OnePanelLayout = new javax.swing.GroupLayout(c2OnePanel);
        c2OnePanel.setLayout(c2OnePanelLayout);
        c2OnePanelLayout.setHorizontalGroup(
            c2OnePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 157, Short.MAX_VALUE)
        );
        c2OnePanelLayout.setVerticalGroup(
            c2OnePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 64, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.2;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(c2OnePanel, gridBagConstraints);

        javax.swing.GroupLayout c2TwoPanelLayout = new javax.swing.GroupLayout(c2TwoPanel);
        c2TwoPanel.setLayout(c2TwoPanelLayout);
        c2TwoPanelLayout.setHorizontalGroup(
            c2TwoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 157, Short.MAX_VALUE)
        );
        c2TwoPanelLayout.setVerticalGroup(
            c2TwoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 160, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(c2TwoPanel, gridBagConstraints);

        javax.swing.GroupLayout c2ThreePanelLayout = new javax.swing.GroupLayout(c2ThreePanel);
        c2ThreePanel.setLayout(c2ThreePanelLayout);
        c2ThreePanelLayout.setHorizontalGroup(
            c2ThreePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 157, Short.MAX_VALUE)
        );
        c2ThreePanelLayout.setVerticalGroup(
            c2ThreePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 64, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.2;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(c2ThreePanel, gridBagConstraints);

        javax.swing.GroupLayout c2FourPanelLayout = new javax.swing.GroupLayout(c2FourPanel);
        c2FourPanel.setLayout(c2FourPanelLayout);
        c2FourPanelLayout.setHorizontalGroup(
            c2FourPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 157, Short.MAX_VALUE)
        );
        c2FourPanelLayout.setVerticalGroup(
            c2FourPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 64, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.2;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(c2FourPanel, gridBagConstraints);

        javax.swing.GroupLayout c2FivePanelLayout = new javax.swing.GroupLayout(c2FivePanel);
        c2FivePanel.setLayout(c2FivePanelLayout);
        c2FivePanelLayout.setHorizontalGroup(
            c2FivePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 157, Short.MAX_VALUE)
        );
        c2FivePanelLayout.setVerticalGroup(
            c2FivePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 64, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.2;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(c2FivePanel, gridBagConstraints);

        javax.swing.GroupLayout c3OnePanelLayout = new javax.swing.GroupLayout(c3OnePanel);
        c3OnePanel.setLayout(c3OnePanelLayout);
        c3OnePanelLayout.setHorizontalGroup(
            c3OnePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 157, Short.MAX_VALUE)
        );
        c3OnePanelLayout.setVerticalGroup(
            c3OnePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 64, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.2;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(c3OnePanel, gridBagConstraints);

        javax.swing.GroupLayout c3TwoPanelLayout = new javax.swing.GroupLayout(c3TwoPanel);
        c3TwoPanel.setLayout(c3TwoPanelLayout);
        c3TwoPanelLayout.setHorizontalGroup(
            c3TwoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 157, Short.MAX_VALUE)
        );
        c3TwoPanelLayout.setVerticalGroup(
            c3TwoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 160, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.2;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(c3TwoPanel, gridBagConstraints);

        javax.swing.GroupLayout c3ThreePanelLayout = new javax.swing.GroupLayout(c3ThreePanel);
        c3ThreePanel.setLayout(c3ThreePanelLayout);
        c3ThreePanelLayout.setHorizontalGroup(
            c3ThreePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 157, Short.MAX_VALUE)
        );
        c3ThreePanelLayout.setVerticalGroup(
            c3ThreePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 64, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.2;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(c3ThreePanel, gridBagConstraints);

        javax.swing.GroupLayout c3FourPanelLayout = new javax.swing.GroupLayout(c3FourPanel);
        c3FourPanel.setLayout(c3FourPanelLayout);
        c3FourPanelLayout.setHorizontalGroup(
            c3FourPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 157, Short.MAX_VALUE)
        );
        c3FourPanelLayout.setVerticalGroup(
            c3FourPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 64, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.2;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(c3FourPanel, gridBagConstraints);

        javax.swing.GroupLayout c3FivePanelLayout = new javax.swing.GroupLayout(c3FivePanel);
        c3FivePanel.setLayout(c3FivePanelLayout);
        c3FivePanelLayout.setHorizontalGroup(
            c3FivePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 157, Short.MAX_VALUE)
        );
        c3FivePanelLayout.setVerticalGroup(
            c3FivePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 64, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.2;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(c3FivePanel, gridBagConstraints);

        javax.swing.GroupLayout c4OnePanelLayout = new javax.swing.GroupLayout(c4OnePanel);
        c4OnePanel.setLayout(c4OnePanelLayout);
        c4OnePanelLayout.setHorizontalGroup(
            c4OnePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 157, Short.MAX_VALUE)
        );
        c4OnePanelLayout.setVerticalGroup(
            c4OnePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 64, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.2;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(c4OnePanel, gridBagConstraints);

        javax.swing.GroupLayout c4TwoPanelLayout = new javax.swing.GroupLayout(c4TwoPanel);
        c4TwoPanel.setLayout(c4TwoPanelLayout);
        c4TwoPanelLayout.setHorizontalGroup(
            c4TwoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 157, Short.MAX_VALUE)
        );
        c4TwoPanelLayout.setVerticalGroup(
            c4TwoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 160, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.2;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(c4TwoPanel, gridBagConstraints);

        javax.swing.GroupLayout c4ThreePanelLayout = new javax.swing.GroupLayout(c4ThreePanel);
        c4ThreePanel.setLayout(c4ThreePanelLayout);
        c4ThreePanelLayout.setHorizontalGroup(
            c4ThreePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 157, Short.MAX_VALUE)
        );
        c4ThreePanelLayout.setVerticalGroup(
            c4ThreePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 64, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.2;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(c4ThreePanel, gridBagConstraints);

        javax.swing.GroupLayout c4FourPanelLayout = new javax.swing.GroupLayout(c4FourPanel);
        c4FourPanel.setLayout(c4FourPanelLayout);
        c4FourPanelLayout.setHorizontalGroup(
            c4FourPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 157, Short.MAX_VALUE)
        );
        c4FourPanelLayout.setVerticalGroup(
            c4FourPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 64, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.2;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(c4FourPanel, gridBagConstraints);

        javax.swing.GroupLayout c4FivePanelLayout = new javax.swing.GroupLayout(c4FivePanel);
        c4FivePanel.setLayout(c4FivePanelLayout);
        c4FivePanelLayout.setHorizontalGroup(
            c4FivePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 157, Short.MAX_VALUE)
        );
        c4FivePanelLayout.setVerticalGroup(
            c4FivePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 64, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.2;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(c4FivePanel, gridBagConstraints);

        javax.swing.GroupLayout c5OnePanelLayout = new javax.swing.GroupLayout(c5OnePanel);
        c5OnePanel.setLayout(c5OnePanelLayout);
        c5OnePanelLayout.setHorizontalGroup(
            c5OnePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 157, Short.MAX_VALUE)
        );
        c5OnePanelLayout.setVerticalGroup(
            c5OnePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 64, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.2;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(c5OnePanel, gridBagConstraints);

        javax.swing.GroupLayout c5TwoPanelLayout = new javax.swing.GroupLayout(c5TwoPanel);
        c5TwoPanel.setLayout(c5TwoPanelLayout);
        c5TwoPanelLayout.setHorizontalGroup(
            c5TwoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 157, Short.MAX_VALUE)
        );
        c5TwoPanelLayout.setVerticalGroup(
            c5TwoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 160, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.2;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(c5TwoPanel, gridBagConstraints);

        javax.swing.GroupLayout c5ThreePanelLayout = new javax.swing.GroupLayout(c5ThreePanel);
        c5ThreePanel.setLayout(c5ThreePanelLayout);
        c5ThreePanelLayout.setHorizontalGroup(
            c5ThreePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 157, Short.MAX_VALUE)
        );
        c5ThreePanelLayout.setVerticalGroup(
            c5ThreePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 64, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.2;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(c5ThreePanel, gridBagConstraints);

        javax.swing.GroupLayout c5FourPanelLayout = new javax.swing.GroupLayout(c5FourPanel);
        c5FourPanel.setLayout(c5FourPanelLayout);
        c5FourPanelLayout.setHorizontalGroup(
            c5FourPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 157, Short.MAX_VALUE)
        );
        c5FourPanelLayout.setVerticalGroup(
            c5FourPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 64, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.2;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(c5FourPanel, gridBagConstraints);

        javax.swing.GroupLayout c5FivePanelLayout = new javax.swing.GroupLayout(c5FivePanel);
        c5FivePanel.setLayout(c5FivePanelLayout);
        c5FivePanelLayout.setHorizontalGroup(
            c5FivePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 157, Short.MAX_VALUE)
        );
        c5FivePanelLayout.setVerticalGroup(
            c5FivePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 64, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.2;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(c5FivePanel, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel c1FivePanel;
    private javax.swing.JPanel c1FourPanel;
    private javax.swing.JPanel c1OnePanel;
    private javax.swing.JPanel c1ThreePanel;
    private javax.swing.JPanel c1TwoPanel;
    private javax.swing.JPanel c2FivePanel;
    private javax.swing.JPanel c2FourPanel;
    private javax.swing.JPanel c2OnePanel;
    private javax.swing.JPanel c2ThreePanel;
    private javax.swing.JPanel c2TwoPanel;
    private javax.swing.JPanel c3FivePanel;
    private javax.swing.JPanel c3FourPanel;
    private javax.swing.JPanel c3OnePanel;
    private javax.swing.JPanel c3ThreePanel;
    private javax.swing.JPanel c3TwoPanel;
    private javax.swing.JPanel c4FivePanel;
    private javax.swing.JPanel c4FourPanel;
    private javax.swing.JPanel c4OnePanel;
    private javax.swing.JPanel c4ThreePanel;
    private javax.swing.JPanel c4TwoPanel;
    private javax.swing.JPanel c5FivePanel;
    private javax.swing.JPanel c5FourPanel;
    private javax.swing.JPanel c5OnePanel;
    private javax.swing.JPanel c5ThreePanel;
    private javax.swing.JPanel c5TwoPanel;
    private javax.swing.JLabel category1Label;
    private javax.swing.JLabel category2Label;
    private javax.swing.JLabel category3Label;
    private javax.swing.JLabel category4Label;
    private javax.swing.JLabel category5Label;
    // End of variables declaration//GEN-END:variables
}
