/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.retrorobots.mainGameGUI;

import org.json.JSONObject;

/**
 *
 * @author KeeganRiley
 */
public class PlayerStats extends javax.swing.JPanel {
    
    private JSONObject player;

    /**
     * Creates new form PlayerStats
     */
    public PlayerStats() {
        initComponents();
        this.player = null;
    }
    
    public PlayerStats(JSONObject player) {
        this();
        this.player = player;
        setLabelValues();
    }

    public void setLabelValues() {
        this.pNameLabel.setText(player.getString("name"));
        this.currScoreLabel.setText(Integer.toString(player.getInt("score")));
        this.roundOneLabel.setText(Integer.toString(player.getInt("roundOneScore")));
        this.roundTwoLabel.setText(Integer.toString(player.getInt("roundTwoScore")));
    }

    public JSONObject getPlayer() {
        return this.player;
    }

    public void setPlayer(JSONObject player) {
        this.player = player;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        pNameLabel = new javax.swing.JLabel();
        currScoreLabel = new javax.swing.JLabel();
        roundOneLabel = new javax.swing.JLabel();
        roundTwoLabel = new javax.swing.JLabel();

        setLayout(new java.awt.GridBagLayout());

        pNameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pNameLabel.setText("jLabel4");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(pNameLabel, gridBagConstraints);

        currScoreLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        currScoreLabel.setText("jLabel5");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(currScoreLabel, gridBagConstraints);

        roundOneLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        roundOneLabel.setText("jLabel6");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(roundOneLabel, gridBagConstraints);

        roundTwoLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        roundTwoLabel.setText("jLabel8");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(roundTwoLabel, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel currScoreLabel;
    private javax.swing.JLabel pNameLabel;
    private javax.swing.JLabel roundOneLabel;
    private javax.swing.JLabel roundTwoLabel;
    // End of variables declaration//GEN-END:variables
}
